server {
	port 8000
	server_name alemafe
	buffer_size 1000000
	root /ourserver
	errorpage_404 errorpages/404.html
	method GET POST DELETE
	location / {
		root /ourserver
		index index.html
		method GET
	}
	location /post_test/ {
		root ourserver/post_test
		method POST
	}
	location /aboutus.html {
		method GET
	}
}